FuelLabs/fuel-explorer

docs/GETTING_STARTED.md

Update requirements to include newer versions of rust, forc, forc index and docker compose.

docs: update requirements section

---

docker/fuel-core/Dockerfile
docker/scripts/start.sh

Run the following PR to ensure that it also works on a MAC.
I assume the previous version was run and it worked on a MAC.
Closes #3

Fix: Update the Dockerfile and start.sh script 

---

package.json
packages/app/.gitignore
packages/app/.storybook/main.ts
packages/app/next.config.mjs
packages/app/package.json
packages/app/stories/HomePage.stories.tsx
packages/app/tsconfig.json
pnpm-lock.yaml
vercel.json

With this PR we now have the preview env with;
- Storybook: https://fuel-explorer-2xwo00p8h-fuel-labs.vercel.app/storybook
- App: https://fuel-explorer-2xwo00p8h-fuel-labs.vercel.app/
We need to fix the storybook to correctly render icons and images...

feat: add preview deployment

---

packages/app/src/systems/Core/components/AssetId/AssetId.stories.tsx
packages/app/src/systems/Core/components/AssetId/AssetId.test.tsx
packages/app/src/systems/Core/components/AssetId/AssetId.tsx
packages/app/src/systems/Core/components/AssetId/index.ts
packages/app/src/systems/Core/components/EntityItem/EntityItem.tsx

feat: add AssetId component

---

package.json
packages/app/package.json
packages/app/src/systems/Core/utils/dayjs.ts
packages/app/src/systems/Home/pages/HomePage.tsx
packages/app/src/systems/Transaction/component/TxCard/TxCard.stories.tsx
packages/app/src/systems/Transaction/component/TxCard/TxCard.tsx
packages/app/src/systems/Transaction/component/TxIcon/TxIcon.stories.tsx
packages/app/src/systems/Transaction/component/TxIcon/TxIcon.tsx
packages/app/src/systems/Transaction/component/TxTitle/TxTitle.stories.tsx
packages/app/src/systems/Transaction/component/TxTitle/TxTitle.tsx
packages/app/src/systems/Transaction/component/__mocks__/tx.ts
packages/app/src/systems/Transaction/types.ts
packages/graphql/.gitignore
packages/graphql/codegen.yml
packages/graphql/graphql.schema.json
packages/graphql/package.json
packages/graphql/tsconfig.json
packages/graphql/tsup.config.ts
pnpm-lock.yaml

⭐ Closes FRO-471
⭐ Closes FRO-472
⭐ Closes FRO-473

feat: add TxCard component and related

---

packages/graphql/src/domains/Input.ts

closes #81 
To test that message inputs now appear you can run the project locally and go to the tx screen with the txId of "0xb09451bce1549f2e2f86009a64e385ce8b45e5e2d71ecdad5f37a910640432e2"

fix: groupedInputs not returning the correct data

---

packages/app/src/systems/Transaction/component/TxInput/TxInput.tsx
packages/app/src/systems/Transaction/component/TxOutput/TxOutput.tsx

closes #71 
you can check this working by going to the tx page for these transactions:
0x8ea0441506d1f33f454f8b9abbb54dc9cfa8fd7583b1a6736af5e87de81ba9a8
0x09e8efd198e8e1183221c40be52c40cef0e2e80377850e7c102837a106452844

feat: add link to contract components

---

packages/app/src/app/block/[id]/page.tsx
packages/app/src/systems/Block/screens/BlockScreen.tsx
packages/graphql/src/domains/Input.ts

feat: add block page header and tabs

---

packages/app/package.json
packages/app/src/app/account/[id]/transactions/page.tsx
packages/app/src/app/transactions/[page]/layout.tsx
packages/app/src/app/transactions/[page]/loading.tsx
packages/app/src/app/transactions/[page]/page.tsx
packages/app/src/app/transactions/[page]/title.tsx
packages/app/src/systems/Core/components/Layout/Layout.tsx
packages/app/src/systems/Core/components/PageTitle/PageTitle.stories.tsx
packages/app/src/systems/Core/components/PageTitle/PageTitle.tsx
packages/app/src/systems/Core/components/Pagination/Pagination.tsx
packages/app/src/systems/Core/components/TopNav/TopNav.tsx
packages/app/src/systems/Home/components/Hero/Hero.tsx
packages/app/src/systems/Transaction/component/TxList/TxList.tsx
packages/ui/src/components/Nav/styles.ts
pnpm-lock.yaml

⭐ Closes [FE-5](https://linear.app/fuel-network/issue/FE-5/home-page-mobile-ui)

feat: add responsive queries for header

---

packages/app/src/systems/Account/components/AccountLayout/AccountLayout.tsx
packages/app/src/systems/Block/screens/BlockScreen.tsx
packages/app/src/systems/Transaction/screens/TxScreen/TxScreen.tsx

Closes FE-29
Fix page headers in Transaction / Account / Block page

fix: page headers

---

packages/app/src/systems/Core/components/Utxos/Utxos.tsx

fix: utxo item component

---

packages/app/src/systems/Transaction/component/TxInput/TxInput.tsx
packages/app/src/systems/Transaction/component/TxOutput/TxOutput.tsx
packages/app/src/systems/Transaction/component/TxScreen/TxScreenAdvanced.tsx
packages/app/src/systems/Transaction/component/TxScreen/TxScreenSimple.tsx
packages/app/src/systems/Transaction/screens/TxScreen/TxScreen.tsx

fix: responsive on transaction page

---

packages/app/src/systems/Transaction/component/TxIcon/TxIcon.tsx
packages/app/src/systems/Transaction/types.ts
packages/graphql/src/domains/Transaction.ts

fix: transaction labeling

---

packages/app/src/systems/Block/actions/get-block.ts
packages/graphql/src/domains/Transaction.ts

fix: block height data inside transaction

---

packages/app/src/systems/Block/components/BlockScreenSimple.tsx
packages/app/src/systems/Block/components/BlockScreenSkeleton.tsx

refactor: remove block page gas spent

---

packages/app/src/systems/Asset/components/AssetItem/AssetItem.tsx

feat: align eth icon

---

packages/app/src/systems/Core/components/BalanceItem/BalanceItem.tsx
packages/app/src/systems/Core/components/Utxos/Utxos.tsx
packages/app/src/systems/Transaction/component/TxInput/TxInput.tsx
packages/app/src/systems/Transaction/component/TxScreen/TxScreenSimple.tsx
packages/app/src/systems/Transaction/component/TxScripts/TxScripts.tsx
packages/ui/src/components/Collapsible/Collapsible.tsx

fix: general responsive fixes

---

packages/graphql/src/domains/Transaction.ts

fix: network fee

---

helm/fuel-explorer/Chart.yaml
helm/fuel-explorer/templates/service.yaml

This PR fixes the formatting used in the Helm Chart `service.yaml` file.

fix: Helm Chart service file

---

packages/app-portal/src/systems/Bridge/pages/BridgeHome.tsx
packages/app-portal/src/systems/Core/components/Header.tsx
packages/app-portal/src/systems/Core/components/Layout.tsx
packages/app-portal/src/systems/Core/styles/core.ts
packages/app-portal/src/systems/Core/styles/scrollbar.css
packages/app-portal/src/systems/Ecosystem/pages/Ecosystem.tsx
packages/app-portal/src/systems/Settings/providers/FuelsUiProvider.tsx

- Layout
- Scrollable
- Header
- BridgeHome (only wrapper part, but not inside with inputs etc)

feat: migrate Layout + Header + BridgeHome

---

packages/app-explorer/.env.example
packages/app-explorer/.env.production
packages/app-explorer/src/app/api/graphql/route.ts
packages/app-explorer/src/systems/Core/utils/sdk.ts
packages/app-explorer/src/systems/Transaction/component/TxScripts/TxScripts.tsx
packages/app-explorer/src/systems/Transactions/components/TxCard/TxCard.tsx
packages/graphql/.dockerignore
packages/graphql/codegen.ts
packages/graphql/src/sdk.ts
packages/graphql/src/server.ts

Add auth `FUEL_EXPLORER_API_KEY` for authenticating use for explorer graphql endpoint.

feat: add api key to GraphQL

---

packages/app-explorer/package.json
packages/app-explorer/src/app/layout.tsx
pnpm-lock.yaml

feat: add vercel analytics

---

packages/app-explorer/package.json
packages/app-portal/src/systems/Bridge/hooks/useBridge.tsx
packages/app-portal/src/systems/Bridge/services/bridge.tsx
packages/app-portal/src/systems/Chains/fuel/containers/FuelVersionDialog.tsx
packages/app-portal/src/systems/Chains/fuel/hooks/useFuelAccountConnection.tsx
packages/app-portal/src/systems/Settings/providers/FuelConnectProvider.tsx
packages/app-portal/src/systems/Settings/providers/FuelUiProvider.tsx
pnpm-lock.yaml

- Fix withdraw (missing argument)
- Fix "add asset to wallet" (it wasn't working too)
- Remove `fuelet` wallet from connector list
| 📷  Demo |
|--------|
| <video src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/fcad4f37-27bc-494b-85d2-c69c7c068a19" />  |

fix: withdraw

---

packages/app-portal/src/systems/Ecosystem/components/EcosystemTags/EcosystemTags.tsx

| Before | After |
|--------|-------|
| <img width="325" alt="Screenshot 2024-02-27 at 12 18 44" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/c8769292-b8a0-4dca-83c0-ee7e6625893a"> | <img width="340" alt="after" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/34597264-5171-4a93-b3d6-4b978a75544d"> |

fix: explorer bg color on dark theme

---

packages/app-explorer/next.config.mjs

Add redirects to the old paths `/portal/<path>` to `/<path>`.

chore: add redirects from portal to new paths

---

.github/workflows/pr-tests.yml
.github/workflows/pr.yaml

chore: use fixed pnpm version 8

---

helm/fuel-explorer/Chart.yaml
helm/fuel-explorer/templates/deployment.yaml

This commit adds support for explorer to consume environment variables from Kubernetes secrets

feat: add Kubernetes secrets support (helm)

---

packages/app-portal/src/systems/Ecosystem/components/EcosystemHeader/EcosystemHeader.tsx
packages/app-portal/src/systems/Ecosystem/data/projects.json

- fix the link of "List your project" button
- remove `isLive` tag from `Aerv`

fix: project Aerv + button typeform (#307)

---

packages/app-portal/src/systems/Ecosystem/data/projects.json

| Demo |
| --- |
| <img width="582" alt="Screenshot 2024-04-23 at 09 28 20" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/60ed5cfb-83ff-406d-8d04-90a55ba1cdf0"> |

fix: add missing tag to the Aerv project

---

packages/app-explorer/src/systems/Core/components/Utxos/Utxos.tsx

After migrating to the testnet, UTXO IDs began returning a value of `34 bytes` instead of the expected `32 bytes` (transaction ID).
This caused the assets list to direct users to a broken transaction page due to the invalid `transaction ID`.
The fix is straightforward: slice the `UTXO ID` to extract only the first 32 bytes (`transaction ID`).
Example of `UTXO Id` and `Transaction ID`:
```tsx
// The last 2 bytes (in this case, 0000) can be removed to extract the transaction ID.
const utxoId = "0x0cc9d936aec9cc0d62e75e1f9a4e8a2e3e651b22fd59f69f5a704bf769237b2f0000";
const __txId = "0x0cc9d936aec9cc0d62e75e1f9a4e8a2e3e651b22fd59f69f5a704bf769237b2f";
```
Documentation: [UTXO ID](https://specs.fuel.network/master/identifiers/utxo-id.html).

fix: extract transaction id (bytes[32]) from utxo id

---

.github/workflows/pr-tests.yml

chore: make pr-tests run on branch release

---

packages/app-explorer/next.config.mjs
packages/app-explorer/src/systems/Core/components/TopNav/TopNav.tsx
packages/app-portal/src/systems/Ecosystem/data/projects.json
packages/graphql/.gitignore
packages/graphql/package.json
packages/graphql/src/schemas/fuelcore.graphql
packages/ui/src/components/Link/Link.tsx
turbo.json

- Closes https://github.com/FuelLabs/fuel-deposits/issues/168
- remove needing to build fuel-core schema
- e2e project link failing
- ui(Link) - make component more pure using the anchor icon inside of <a> element

feat: include header with Deposits link

---

packages/app-explorer/src/systems/Transaction/__mocks__/tx.ts
packages/app-portal/src/systems/Accounts/components/AccountConnectionInput/AccountConnectionInput.stories.tsx
packages/app-portal/src/systems/Chains/fuel/containers/FuelAccountConnection.tsx
packages/ui/src/components/Nav/Nav.stories.tsx

- Closes #382 
Converting bech32 address in Bridge visual components

feat: convert bech32 address to b256

---

packages/app-explorer/src/systems/Core/components/TopNav/TopNav.tsx

- change "anchor icon" to use a → arrow instead 
- make alert and link font the same

chore(ui): add arrow to "Learn more" link

---

packages/app-explorer/src/systems/Core/components/ViewMode/ViewMode.tsx
packages/app-portal/src/systems/Settings/providers/FuelConnectProvider.tsx
packages/ui/src/components/ToggleGroup/ToggleGroup.tsx

Closes #411 
- Implemented href support on `ToggleGroup` component, with native support to Next.js prefetching
- ToggleGroup is now SSR and SSG compatible
- Fixes prefetching not working properly 
https://github.com/user-attachments/assets/3bfae94a-ab90-481c-bb34-2fbafd0aab5e

feat: Toggle Group SSR and SSG compatible with prefetching

---

packages/app-explorer/package.json
packages/app-explorer/src/app/globals.css
packages/app-explorer/src/systems/Asset/hooks/useFuelAsset.ts
packages/app-explorer/src/systems/Core/utils/asset.ts
pnpm-lock.yaml

fix: formatting base asset on testnet (2)

---

packages/app-explorer/package.json
packages/app-explorer/src/systems/Core/components/JsonViewer/JsonViewer.tsx
packages/app-explorer/src/systems/Transaction/component/TxScreen/TxScreenAdvanced.tsx
packages/app-explorer/src/systems/Transaction/component/TxScripts/TxScripts.tsx
pnpm-lock.yaml

Closes #412 
- Fixes CodeBlock not loading properly on Block advanced inspector.
- Fixes required CSS not always loading when rendering the code block
- Updated `react-json-view-lite` to bring latest bug fixes

fix: non-interactive CodeBlock component on advanced Block inspector 

---

packages/app-portal/src/systems/Chains/eth/services/txEthToFuel.ts
packages/app-portal/src/systems/Chains/fuel/services/txFuelToEth.ts

fix(bridge): change pagination limit of graphql requests

---

packages/graphql/.gitignore

including a missing log folder which breaks when running backend

fix: missing log folder

---

packages/graphql/src/application/uc/NewAddBlockRange.ts
packages/graphql/src/graphql/resolvers/PredicateResolver.ts

fix: preventing 0x predicates to being showed and persisted

---

packages/app-portal/src/systems/Ecosystem/data/projects.json

Updated the following projects:
- Superchain: Updated to Pangea
- Catalyst: Updated URL

docs: updated projects

---

helm/fuel-explorer/Chart.yaml
helm/fuel-explorer/templates/servicemonitor.yaml
helm/fuel-explorer/values.yaml

Adding service monitor to helm chart

feat: Adding service monitor to helm chart

---

packages/ui/package.json
packages/ui/tsup.config.mjs
pnpm-lock.yaml

- Without this config, importing @fuels/ui was breaking

fix: add some deps as external

---

.changeset/five-experts-give.md

- Adds a changeset to PR https://github.com/FuelLabs/fuel-explorer/pull/550 changes

docs: add a changeset for the external deps change

---

packages/app-explorer/src/systems/Core/components/Search/SearchForm.tsx
packages/app-explorer/src/systems/Core/components/Search/SearchInput/SearchInput.tsx
packages/app-explorer/src/systems/Core/components/Search/SearchInput/styles.ts
packages/app-explorer/src/systems/Core/components/Search/SearchWidget.tsx
packages/app-explorer/src/systems/Core/components/TopNav/TopNav.tsx
packages/app-explorer/src/systems/Home/components/Hero/Hero.tsx

Closes #560 
- Moved search bar to header
https://github.com/user-attachments/assets/0f593cba-d1af-4a48-822e-bf9eae263ebb

feat: move searchbar to header

---

packages/graphql/src/graphql/generated/sdk.ts
packages/graphql/src/graphql/queries/sdk/blocks.graphql
packages/graphql/src/infra/dao/Block.ts

- added daHeight for blocks UI

fix: added daHeight to blocks UI

---

packages/graphql/ASSETS.md

create docs for Assets API endpoint

feat: create docs for Assets API endpoint
