FuelLabs/fuel-explorer

docker/docker-compose.yaml
Update pgsql exposed port to avoid conflicts with other PostgreSQL processes running on the host machine.
=> chore: update pgsql exposed port

packages/app/src/app/account/[id]/predicate/page.tsx, packages/app/src/systems/Account/actions/get-predicate.ts, packages/app/src/systems/Core/components/Utxos/Utxos.tsx, packages/app/src/systems/Transaction/component/TxInput/TxInput.tsx, packages/app/src/systems/Transaction/component/TxOutput/TxOutput.tsx, packages/app/src/systems/Transaction/component/TxScripts/TxScripts.tsx, packages/graphql/codegen.ts, packages/graphql/src/domains/Transaction.ts, packages/ui/src/components/Address/Address.tsx
Closes FE-24
Adding `defaultScalarType: string` as most cases will be string:
```
ID
String
Address
AssetId
BlockId
Bytes32
ContractId
HexString
MessageId
Nonce
Salt
Signature
Tai64Timestamp
TransactionId
TxPointer
U32
U64
UtxoId
```
Also adding specific scalar config for:
```
Boolean: 'boolean',
Int: 'number',
```
=> feat: add scalar config

packages/app/src/systems/Asset/components/AssetItem/AssetItem.stories.tsx, packages/app/src/systems/Asset/components/AssetItem/AssetItem.tsx, packages/app/src/systems/Core/components/BalanceItem/BalanceItem.tsx, packages/app/src/systems/Transaction/component/TxIcon/TxIcon.tsx, packages/app/src/systems/Transaction/component/TxInput/TxInput.tsx, packages/app/src/systems/Transaction/component/TxOutput/TxOutput.stories.tsx, packages/app/src/systems/Transaction/component/TxOutput/TxOutput.tsx
=> chore: adjust asset item

packages/app/src/systems/Core/components/Pagination/Pagination.tsx, packages/ui/src/components/Button/Button.stories.tsx, packages/ui/src/components/Button/Button.tsx, packages/ui/src/components/IconButton/IconButton.stories.tsx, packages/ui/src/components/IconButton/IconButton.tsx
=> feat: add cursors where applicable

packages/app-explorer/src/systems/Core/components/Provider/Provider.tsx, packages/app-explorer/src/systems/Core/components/Theme/Theme.tsx, packages/app-explorer/src/systems/Core/components/Theme/ThemeDefault.tsx, packages/app-explorer/src/systems/Core/components/Theme/index.tsx, packages/app-explorer/src/systems/Core/components/TopNav/TopNav.tsx, packages/app-portal/.env.production, packages/app-portal/src/config.ts, packages/app-portal/src/systems/Bridge/hooks/useExplorerLink.tsx, packages/app-portal/src/vite-env.d.ts, packages/app-portal/vite.config.ts, packages/ui/package.json, packages/ui/src/components/Nav/Nav.tsx, pnpm-lock.yaml
On this PR;
- Add a force component that setTheme if undefined to ensure the theme is on localStorage
- Once theme on storage changes both application receive the new theme
- Remove the need for next-themes inside `@fuels/ui`
=> feat: make theme configuration work cross applications

packages/app-portal/src/systems/Chains/eth/hooks/useEthAccountConnection.tsx, packages/app-portal/src/systems/Chains/fuel/containers/TxFuelToEthDialog.tsx, packages/app-portal/src/systems/Overlay/components/OverlayDialog/OverlayDialog.tsx, packages/app-portal/src/systems/Overlay/hooks/useOverlay.tsx
On this PR;
- Add a setting configuration object to pass data around overlay action this is required to pass the data at the time Dialog should close check happens.
- This solves the issue where user is required to confirm TX but ETH Wallet is not connected. Creating the flow of asking first to connect, and them keeping the user on the screen to finish the action.
=> fix: connect wallet before confirm if not connected

packages/app-explorer/package.json, pnpm-lock.yaml, turbo.json
Ensure app-explorer is built after app-portal has finish the build process by adding a dependency on package.json, also adds the completely path of the outputs on turbo.json to avoid incorrect cache.
=> fix: ensure order of build and complete output paths

packages/app-explorer/src/systems/Core/components/TopNav/TopNav.tsx, packages/ui/src/components/Nav/Nav.tsx
Removes an unused `data-theme` that was firing a hydration error.
=> fix: resolve html hydration issue

packages/app-portal/src/systems/Bridge/components/BridgeSteps/BridgeSteps.tsx, packages/app-portal/src/systems/Bridge/components/BridgeTxItem/BridgeTxItem.tsx, packages/app-portal/src/systems/Bridge/components/BridgeTxItemsLoading/BridgeTxItemsLoading.tsx, packages/app-portal/src/systems/Bridge/components/BridgeTxOverview/BridgeTxOverview.tsx, packages/app-portal/src/systems/Bridge/hooks/useBridgeTxs.tsx, packages/app-portal/src/systems/Bridge/pages/BridgeTxList.tsx, packages/app-portal/src/systems/Chains/fuel/components/ActionRequiredBadge/ActionRequiredBadge.tsx, packages/app-portal/src/systems/Chains/fuel/containers/TxFuelToEthDialog.tsx, packages/app-portal/src/systems/Chains/fuel/containers/TxListItemFuelToEth.tsx
A few improvements on the transaction list and popup.
- Increasing table's size.
- Making the loading-state looks better.
- Text alignments.
- New pagination size (5 txns per page)
| 📷  Demo |
| ----- |
| <img width="489" alt="padding" src="https://github.com/FuelLabs/fuel-explorer/assets/7074983/022c940f-74bb-488b-b56a-11ebdd683b61"> |
=> fix: bridge polishing

packages/app-portal/src/systems/Chains/eth/hooks/useTxEthToFuel.tsx, packages/app-portal/src/systems/Chains/eth/utils/deepCompare.ts
Fix the comparison that was crashing the xstate selector because of a `Window` instance inside the `Fuel` class.
=> fix: resolve window stringify

packages/app-commons/src/config.ts, packages/app-portal/src/systems/Bridge/hooks/useExplorerLink.tsx, packages/app-portal/src/systems/Chains/eth/hooks/useTxEthToFuel.tsx, packages/app-portal/src/systems/Chains/fuel/hooks/useTxFuelToEth.tsx
Remove unused environment variable that was sending the user to an `undefined` path.
=> fix: return only valid links

.github/workflows/docker-publish.yml, .vscode/settings.json, deployment/Dockerfile, packages/graphql/.env.example, packages/graphql/.env.production, packages/graphql/README.md, packages/graphql/codegen.fuel.ts, packages/graphql/package.json, packages/graphql/src/process.env.d.ts, packages/graphql/src/server.ts, packages/graphql/tsup.config.mjs, pnpm-lock.yaml
Revert change on graphql package related to provider URL, the graphql package uses a customizable providerUrl that doesn't match the pre-defined one. Also the graphql package is not a next.js package removing the need for pre fixed PUBLIC_NEXT env variables.
=> fix: revert changes on providerUrl config

.github/workflows/pr-tests.yml, .github/workflows/pr.yaml, packages/app-portal/src/systems/Chains/eth/hooks/useEthBalance.tsx, packages/e2e-tests/playwright.config.ts
The current implementation of the block watcher trigger multiples request at the same time increasing data usage
=> fix: remove block watcher to refresh balance

packages/app-explorer/src/systems/Core/components/Search/SearchInput.tsx
| Before | After |
---|---
| <img width="1093" alt="Screenshot 2024-04-26 at 14 54 03" src="https://github.com/FuelLabs/fuel-explorer/assets/114662397/76d43ef1-19c3-40a9-807c-5d6a6b22aa63"> | <img width="1093" alt="Screenshot 2024-04-26 at 14 54 03" src="https://github.com/FuelLabs/fuel-explorer/assets/3487334/8ecf494b-7081-4e99-9a08-a31818e69790"> |
=> fix: search error layout breaking on long inputs

packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutput.tsx, packages/graphql/src/domains/Output.ts, packages/graphql/src/queries/tx-fragments.graphql, packages/graphql/src/services/extends.graphql
Fixing the format of the `contractId` in the `ContractCreated` output. 
Previously, the `contractId` was an object (`contract.id`) in `beta-5`. 
With this update, it will be a regular string, consistent with the format used in the `testnet`.
=> fix: sync output contract created with the new response

packages/graphql/src/domains/Operation.ts, packages/graphql/src/queries/tx-fragments.graphql
Closes #362 
before: https://app.fuel.network/tx/0xcc7335e031ea4728d6e8520ddec782140b7d5fd6fe94a080a6009bd1bf8b82c4/simple
after (fixed):  https://fuel-explorer-7hcl73n0d-fuel-labs.vercel.app/tx/0xcc7335e031ea4728d6e8520ddec782140b7d5fd6fe94a080a6009bd1bf8b82c4/simple
=> fix: show correct operations for contract calls in block explorer

packages/app-explorer/src/systems/Transaction/__mocks__/tx.ts, packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutput.tsx, packages/graphql/src/domains/Output.ts, packages/graphql/src/domains/Transaction.ts, packages/graphql/src/queries/tx-fragments.graphql, packages/graphql/src/services/extends.graphql
This reverts commit `54ff2a423a73d7116d2fcb890d6e3d643aeafe6d`.
(Adding back `groupedOutputs` to the graphql package that was removed in this PR https://github.com/FuelLabs/fuel-explorer/pull/433)
- This PR relates to https://github.com/FuelLabs/fuel-explorer/issues/431
=> fix: revert "grouped outputs removal"

packages/app-portal/src/systems/Ecosystem/components/ProjectList/ProjectList.tsx, packages/app-portal/src/systems/Ecosystem/data/projects.json
- Closes #489 
- Fix issue on rendering projects as the key was only using the `project.url` , causing problems when more than 1 project have the same URL
- Change tags of Bako Safe project
=> fix: render issue in projects + change some projects details

packages/app-portal/src/systems/Ecosystem/components/EcosystemHeader/EcosystemHeader.tsx, packages/app-portal/src/systems/Ecosystem/components/ProjectItem/ProjectItem.tsx, packages/app-portal/src/systems/Ecosystem/data/projects.json, packages/app-portal/src/systems/Ecosystem/hooks/useEcosystem.tsx, packages/app-portal/src/systems/Ecosystem/machines/ecosystemMachine.tsx, packages/app-portal/src/systems/Ecosystem/pages/Ecosystem.tsx, packages/app-portal/src/systems/Ecosystem/types.ts
- Closes #471 
- Closes #527 
- Closes #528 
Added "Featured" option to projects
- Featured will show highlighted with a yellow border + yellow "Featured" tag
- Featured will be ordered first
- Added toggle to select if will show only "Live" projects or if it will show "Building" also
- Make "Building Projects" a bit less highlighted
These are the initial projects setup as "Featured"
```
Mira (DEX)
Swaylend (Lending)
Spark (Order Book)
Griffy (Prediction Market)
Thunder (NFT Marketplace)
Fluid (Stablecoin)
```
=> feat: add featured projects

packages/app-explorer/src/systems/Asset/components/AssetItem/AssetItem.tsx, packages/app-explorer/src/systems/Core/components/Amount/Amount.tsx, packages/app-explorer/src/systems/Transaction/component/TxIcon/TxIcon.tsx, packages/app-explorer/src/systems/Transaction/component/TxInput/TxInputCoin/TxInputCoin.tsx, packages/app-explorer/src/systems/Transaction/component/TxInput/TxInputContract/TxInputContract.tsx, packages/app-explorer/src/systems/Transaction/component/TxInput/TxInputMessage/TxInputMessage.tsx, packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutput.tsx, packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutputCoin.tsx, packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutputContractCreated.tsx, packages/app-explorer/src/systems/Transaction/component/TxOutput/TxOutputContractOutput.tsx, packages/app-explorer/src/systems/Transaction/component/TxOutput/constants.ts, packages/app-explorer/src/systems/Transaction/component/TxOutput/styles.ts, packages/app-explorer/src/systems/Transaction/component/TxOutput/types.ts, packages/app-explorer/src/systems/Transaction/component/TxScreen/TxScreenSimple.tsx, packages/app-explorer/src/systems/Transaction/component/TxScripts/TxReceiptAmount.tsx, packages/app-explorer/src/systems/Transaction/component/TxScripts/TxReceiptBadge/TxReceiptBadge.tsx, packages/app-explorer/src/systems/Transaction/component/TxScripts/TxReceiptHeader/TxReceiptHeader.tsx, packages/app-explorer/src/systems/Transaction/component/TxScripts/TxReceiptHeader/constants.ts, packages/app-explorer/src/systems/Transaction/component/TxScripts/TxReceiptHeader/types.ts, packages/app-explorer/src/systems/Transaction/types.ts, packages/graphql/src/domain/Transaction/ReceiptsParserAdapter.ts, packages/graphql/src/domain/Transaction/TransactionEntity.ts, packages/graphql/src/domain/Transaction/factories/GroupedReceiptsFactory.ts, packages/graphql/src/graphql/generated/sdk-provider.ts, packages/graphql/src/graphql/generated/sdk.ts, packages/graphql/src/graphql/schemas/explorer.graphql, packages/ui/src/components/Address/Address.tsx
Closes #533 
- Receipts without a root operation are now included in the `operations` array with a new type `Rootless`
- [Fix] Not displaying `MESSAGE_OUT` receipts from operations, now all receipts present are rendered in operations;
- [Fix] Not displaying `ContractOutput` and `VariableOutput`
- [Refactor] All Inputs, Operations and Outputs now display information in the same pattern (e.g. Text & Icon badges, amounts, information positioning, etc)
=> refactor: transaction screen

.github/workflows/pr-tests.yml, docker/docker-compose.yml, docker/fuel-core/Dockerfile, docker/fuel-core/fuel_core.sh
- Fixes Fuel Core container waiting indefinitely
- Fixes Fuel Core using wrong chain config
- Fuel Core now waits for l1's `service_healthy` instead of `service_started`
=> fix: fuel core chain config

.changeset/wet-houses-perform.md, .github/workflows/release-npm-changeset.yml, package.json, packages/ui/package.json
`@fuels/ui` was being published to npm without its dist folder, after a long search I found out that `pnpm changeset publish` wasn't building the package and there were no actions in the CI's pipeline that built the package.
- Adds `pnpm build:lib` before publishing
- Fixes a typo in the UI's package json
=> fix: build package before publishing

packages/app-explorer/.env.example, packages/app-explorer/next.config.mjs
Since we're not exposing this production domain anymore, let's remove it from SEO robots.
=> feat: add noindex to the header
